// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
dotenv.config({ path: ".env.local" });
dotenv.config(); // fallback to .env
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Use DIRECT_URL (session-mode pooler, port 5432) for migrations.
    // Falls back to DATABASE_URL for local dev where DIRECT_URL may not be set.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
